version: "3.8"

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: animegination
      volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
